Repository MegaMek/megameklab, pull requests merged in 2025-05, with the labels that each got.

#1868 fix: resets walk MP to 0 when setting an SV engine as None
  megameklab/src/megameklab/ui/supportVehicle/SVStructureTab.java
Labels: Support Vees, Severity: Low

#1891 fix: checks if OS is mac and dont load the html for the recent files in the menu bar
  megameklab/src/megameklab/ui/MenuBar.java
  megameklab/src/megameklab/ui/util/OSUtil.java
Labels: GUI, Mac

#1882 Updated Gradle to 8.14.
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  megameklab/build.gradle
Labels: For New Dev Cycle

#1821 Tip of the Day
  megameklab/docs/history.txt
  megameklab/resources/megameklab/resources/Splash.properties
  megameklab/resources/megameklab/resources/TipOfTheDay.properties
  megameklab/src/megameklab/ui/StartupGUI.java
Labels: (RFE) Enhancement
